models:
  videmoae_ssv2_short:
    model_name: 'MCG-NJU/videomae-base-short-ssv2'
    use_text: false
  videomae_ssv2:
    model_name: 'MCG-NJU/videomae-base-ssv2'
    use_text: false

  videomae_kinetics:
    model_name: 'MCG-NJU/videomae-base-finetuned-kinetics'
    use_text: false
  xclip:
    model_name: 'microsoft/xclip-base-patch32-16-frames'
    use_text: false
    text_prompts: []
